cmd/main.go
utils/chainops.go

feat: add unsubscribe command

---

README.md
config_holesky.toml
config_mainnet.toml

- Update image tag in the config files
- Add information to the readme

update image tag and readme

---

cmd/main.go
config/config.go
utils/docker.go

Closes: #41
---
- @kashishshah

chore: display the network name in the config, docker container name

---

.github/workflows/lint.yml
.github/workflows/push-docker.yml
.github/workflows/test.yml

---
- @kashishshah 
- @mastereng12

chore: remove `main` from ci

---

cmd/main.go
utils/keystore.go
utils/utils.go

Closes: #58
Instead of the hidden password input, it uses the password file path. The path allows us to not reveal the password and keep the non-interaction feature.
---
- @kashishshah

password path

---

.github/workflows/lint.yml
.github/workflows/push-docker.yml
.github/workflows/test.yml
README.md
cmd/main.go
config/config.go
config/default.go
go.mod
go.sum
utils/docker.go
utils/keystore.go
utils/utils.go

release: support Arbitrum

---

script/register-operator.sh

fix typo in comment

---

monitoring/alerting/lagrange-alerts.json
monitoring/dashboards/lagrange-metrics.json

Closes: #75
---
- @kashishshah

feat: add Grafana dashboard and alerts

---

monitoring/MONITORING.MD
monitoring/dashboards/lagrange-metrics.json
monitoring/prometheus.yml

Closes: #78
- Fix metrics to show graphs on Grafana dashboard
- Add monitoring readme
---

fix metrics for grafana dashboard and add readme

---

cmd/main.go
config.toml
config/config.go
config/default.go
monitoring/MONITORING.MD
monitoring/alerting/lagrange-alerts.json
monitoring/dashboards/dashboard_provider.yaml
monitoring/dashboards/lagrange-metrics.json
monitoring/datasources/datasource.yml
monitoring/docker-compose.yml
monitoring/prometheus.yml
utils/docker.go

Closes: #70 
---
- @kashishshah

feat: add monitoring config

---

README.md
cmd/main.go

Closes: #77
---
- @kashishshah

feat: add command to deploy with config

---

README.md
cmd/main.go
config/config.go

Closes: #92
---
- @kashishshah 
- @cool-develope

chore: ensure config file path

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
README.md

add issue templates and remove redundant data from readme

---

cmd/main.go
config.toml
config/config.go
config/default.go
templates/client_config.toml

new configs under `Telemetry`
- `MetricsEnabled` :  manage the metrics on or off
- `MetricsServerPort`: manage the metrics server port
---

chore: sync node config updates

---

README.md
templates/docker-compose.yml

chore: update README

---

cmd/main.go
config.toml
config/config.go
config/default.go
templates/docker-compose.yml
utils/docker.go

fix: expose the host binding port in the config

---

cmd/main.go
config/config.go
config/default.go
config_bulk.toml
utils/utils.go

add new command & config for bulk node deployment

---

cmd/main.go
config/config.go
config_signer.toml
utils/docker.go

Closes: #123
new command: 
```
go run ./cmd/ deploy-signer -c ./config_signer.toml -i lagrangelabs/lagrange-node:develop
```
---

feat: add the command to spin up the Signer

---

go.mod
go.sum

chore: fixed the node submodule deps

---

script/ext.conf
script/generate-cert.sh

Closes: https://github.com/Lagrange-Labs/lsc-query-layer/issues/216
---

feat: add the script to generate the TLS cert

---

README.md
cmd/main.go

add the command to generate the config

---

CHANGELOG.md
README.md
cmd/main.go
script/ext.conf
script/generate-cert.sh

release v1.1.3
